<template><div><!--
 * @Author: 可以清心
 * @Description: 
 * @Date: 2022-11-08 14:09:52
 * @LastEditTime: 2022-11-09 10:06:52
-->
<h1 id="自开发徽章组件" tabindex="-1"><a class="header-anchor" href="#自开发徽章组件" aria-hidden="true">#</a> 自开发徽章组件</h1>
<h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍" aria-hidden="true">#</a> 介绍</h2>
<ul>
<li>一个根据字段生成右上角徽标的组件</li>
<li>支持自定义徽标(需在任意开发包内上传对应的 <code v-pre>svg</code>)</li>
<li>支持识别的字段目前有单行输入、下拉框(数据字典格式)、数据选择和虚拟字段</li>
</ul>
<h2 id="预览" tabindex="-1"><a class="header-anchor" href="#预览" aria-hidden="true">#</a> 预览</h2>
<p><img src="/component/4.jpeg" alt="image"></p>
<h2 id="基本配置" tabindex="-1"><a class="header-anchor" href="#基本配置" aria-hidden="true">#</a> 基本配置</h2>
<p>完整配置(?表示可选属性)</p>
<div class="language-json line-numbers-mode" data-ext="json"><pre v-pre class="language-json"><code><span class="token punctuation">{</span>
    <span class="token property">"componentType"</span><span class="token operator">:</span> <span class="token string">"FORM_TEXT_INPUT | FORM_SELECT_INPUT | FORM_VIRTUAL_FIELD ｜ FORM_DATA_SELECTOR"</span><span class="token punctuation">,</span>
    <span class="token property">"model?"</span><span class="token operator">:</span> <span class="token string">"模型字段"</span><span class="token punctuation">,</span>
    <span class="token property">"uuid?"</span><span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">,</span>
    <span class="token property">"config"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
        <span class="token punctuation">[</span><span class="token string">"COMPLETED"</span><span class="token punctuation">,</span> <span class="token string">"已完成"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"APPROVING"</span><span class="token punctuation">,</span> <span class="token string">"审批中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"REJECTED"</span><span class="token punctuation">,</span> <span class="token string">"已拒绝"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"WITHDRAWN"</span><span class="token punctuation">,</span> <span class="token string">"已撤回"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"TERMINATED"</span><span class="token punctuation">,</span> <span class="token string">"已终止"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"UNDONE"</span><span class="token punctuation">,</span> <span class="token string">"已撤销"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"ARCHIVED"</span><span class="token punctuation">,</span> <span class="token string">"已归档"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"DECLARE_DEADLINE"</span><span class="token punctuation">,</span> <span class="token string">"申报截止"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"DECLARING"</span><span class="token punctuation">,</span> <span class="token string">"申报中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"REVIEWING"</span><span class="token punctuation">,</span> <span class="token string">"评审中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"UNSTART"</span><span class="token punctuation">,</span> <span class="token string">"未开始"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"PASS"</span><span class="token punctuation">,</span> <span class="token string">"通过"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"NORMAL"</span><span class="token punctuation">,</span> <span class="token string">"普通"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"URGENT"</span><span class="token punctuation">,</span> <span class="token string">"加急"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"EMERGENCY"</span><span class="token punctuation">,</span> <span class="token string">"紧急"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"NOSCORE"</span><span class="token punctuation">,</span> <span class="token string">"未评分"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"SCORE"</span><span class="token punctuation">,</span> <span class="token string">"已评分"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"CHECKING"</span><span class="token punctuation">,</span> <span class="token string">"待审核"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"CHECK_ERROR"</span><span class="token punctuation">,</span> <span class="token string">"验证失败"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"APPLYING"</span><span class="token punctuation">,</span> <span class="token string">"申请中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"CHECKED"</span><span class="token punctuation">,</span> <span class="token string">"已审核"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"APPLIED"</span><span class="token punctuation">,</span> <span class="token string">"已申请"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"ONJOB"</span><span class="token punctuation">,</span> <span class="token string">"在职"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"DISPOSED"</span><span class="token punctuation">,</span> <span class="token string">"已办结"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"REPLIED"</span><span class="token punctuation">,</span> <span class="token string">"已回复"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"APPLYSUCCESS"</span><span class="token punctuation">,</span> <span class="token string">"申请成功"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"UNPUBLISH"</span><span class="token punctuation">,</span> <span class="token string">"未发布"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"READ"</span><span class="token punctuation">,</span> <span class="token string">"已读"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"UNREAD"</span><span class="token punctuation">,</span> <span class="token string">"未读"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"BACK"</span><span class="token punctuation">,</span> <span class="token string">"回退"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"WAITREPLY"</span><span class="token punctuation">,</span> <span class="token string">"待回复"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"PUBLISHING"</span><span class="token punctuation">,</span> <span class="token string">"公示中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"NOPASS"</span><span class="token punctuation">,</span> <span class="token string">"未通过"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">[</span><span class="token string">"DISPOSING"</span><span class="token punctuation">,</span> <span class="token string">"处理中"</span><span class="token punctuation">]</span>
    <span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token property">"extraConfig"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
        <span class="token punctuation">[</span><span class="token string">"w-todo"</span><span class="token punctuation">,</span> <span class="token string">"待办"</span><span class="token punctuation">]</span>
    <span class="token punctuation">]</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1、componenttype" tabindex="-1"><a class="header-anchor" href="#_1、componenttype" aria-hidden="true">#</a> 1、<code v-pre>componentType</code></h3>
<p><code v-pre>componentType</code> 需要识别字段的组件类型</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">type</span> <span class="token class-name">ComponentType</span> <span class="token operator">=</span> <span class="token string">"FORM_TEXT_INPUT"</span> <span class="token operator">|</span> <span class="token string">"FORM_SELECT_INPUT"</span> <span class="token operator">|</span> <span class="token string">"FORM_VIRTUAL_FIELD"</span> ｜ <span class="token string">"FORM_DATA_SELECTOR"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_2、model" tabindex="-1"><a class="header-anchor" href="#_2、model" aria-hidden="true">#</a> 2、<code v-pre>model</code></h3>
<p><code v-pre>model</code> 模型编码(<code v-pre>modeField</code>)，当组件类型不是虚拟字段时必须存在</p>
<h3 id="_3、uuid" tabindex="-1"><a class="header-anchor" href="#_3、uuid" aria-hidden="true">#</a> 3、<code v-pre>uuid</code></h3>
<p><code v-pre>uuid</code>，当组件类型是虚拟字段的时候必须指定 <code v-pre>uuid</code>，因为不存在模型编码</p>
<h3 id="_4、config" tabindex="-1"><a class="header-anchor" href="#_4、config" aria-hidden="true">#</a> 4、<code v-pre>config</code></h3>
<p><code v-pre>config</code>，一些预设的配置</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">"COMPLETED"</span><span class="token punctuation">,</span> <span class="token string">"已完成"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"APPROVING"</span><span class="token punctuation">,</span> <span class="token string">"审批中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"REJECTED"</span><span class="token punctuation">,</span> <span class="token string">"已拒绝"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"WITHDRAWN"</span><span class="token punctuation">,</span> <span class="token string">"已撤回"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"TERMINATED"</span><span class="token punctuation">,</span> <span class="token string">"已终止"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"UNDONE"</span><span class="token punctuation">,</span> <span class="token string">"已撤销"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"ARCHIVED"</span><span class="token punctuation">,</span> <span class="token string">"已归档"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"DECLARE_DEADLINE"</span><span class="token punctuation">,</span> <span class="token string">"申报截止"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"DECLARING"</span><span class="token punctuation">,</span> <span class="token string">"申报中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"REVIEWING"</span><span class="token punctuation">,</span> <span class="token string">"评审中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"UNSTART"</span><span class="token punctuation">,</span> <span class="token string">"未开始"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"PASS"</span><span class="token punctuation">,</span> <span class="token string">"通过"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"NORMAL"</span><span class="token punctuation">,</span> <span class="token string">"普通"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"URGENT"</span><span class="token punctuation">,</span> <span class="token string">"加急"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"EMERGENCY"</span><span class="token punctuation">,</span> <span class="token string">"紧急"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"NOSCORE"</span><span class="token punctuation">,</span> <span class="token string">"未评分"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"SCORE"</span><span class="token punctuation">,</span> <span class="token string">"已评分"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"CHECKING"</span><span class="token punctuation">,</span> <span class="token string">"待审核"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"CHECK_ERROR"</span><span class="token punctuation">,</span> <span class="token string">"验证失败"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"APPLYING"</span><span class="token punctuation">,</span> <span class="token string">"申请中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"CHECKED"</span><span class="token punctuation">,</span> <span class="token string">"已审核"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"APPLIED"</span><span class="token punctuation">,</span> <span class="token string">"已申请"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"ONJOB"</span><span class="token punctuation">,</span> <span class="token string">"在职"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"DISPOSED"</span><span class="token punctuation">,</span> <span class="token string">"已办结"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"REPLIED"</span><span class="token punctuation">,</span> <span class="token string">"已回复"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"APPLYSUCCESS"</span><span class="token punctuation">,</span> <span class="token string">"申请成功"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"UNPUBLISH"</span><span class="token punctuation">,</span> <span class="token string">"未发布"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"READ"</span><span class="token punctuation">,</span> <span class="token string">"已读"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"UNREAD"</span><span class="token punctuation">,</span> <span class="token string">"未读"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"BACK"</span><span class="token punctuation">,</span> <span class="token string">"回退"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"WAITREPLY"</span><span class="token punctuation">,</span> <span class="token string">"待回复"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"PUBLISHING"</span><span class="token punctuation">,</span> <span class="token string">"公示中"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"NOPASS"</span><span class="token punctuation">,</span> <span class="token string">"未通过"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string">"DISPOSING"</span><span class="token punctuation">,</span> <span class="token string">"处理中"</span><span class="token punctuation">]</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>它将被用作 <code v-pre>map</code> 输出，所以 <code v-pre>key</code> 不能重复，否则会被覆盖</li>
<li><code v-pre>key</code> 表示上方的预设(<code v-pre>preset</code>)，<code v-pre>value</code> 表示该 <code v-pre>model</code> 对应字段的数据，例如单行输入是普通的时候，详细会加上普通(NORMAL)徽标</li>
<li>需要注意的是，如果是下拉框识别的是选项编码，所以对应的 <code v-pre>value</code> 也应该是选项编码</li>
<li>上述都是预设，本身自开发组件已存在图标</li>
</ul>
<h3 id="_5、extraconfig" tabindex="-1"><a class="header-anchor" href="#_5、extraconfig" aria-hidden="true">#</a> 5、<code v-pre>extraConfig</code></h3>
<p><code v-pre>extraConfig</code>，额外的配置，这里是指你可以自定义徽标的形式，只需要在任意自开发包中上传对应的 <code v-pre>svg</code> 即可。当然需要注意下面的规则 👇</p>
<ul>
<li>因为是自定义那么 <code v-pre>key</code> 就是你的 <code v-pre>svg</code> 文件的文件名，<code v-pre>value</code> 依然是对应 <code v-pre>model</code> 可能取到的值，如果是这个值，显示对应的徽标</li>
<li>在其他自开发包中如果需要上传自己的 <code v-pre>svg</code> 使用，请在 <code v-pre>custom/index.js</code> 中添加以下代码</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token string">'@/icons/index'</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="todo" tabindex="-1"><a class="header-anchor" href="#todo" aria-hidden="true">#</a> todo</h2>
<l-checkbox color="red" content="还没想好......" /><h2 id="下载" tabindex="-1"><a class="header-anchor" href="#下载" aria-hidden="true">#</a> 下载</h2>
<l-download title="自开发包下载" link="https://share.weiyun.com/56BeVbTj" /></div></template>


